#+hugo_base_dir: ../../
#+hugo_section: linknotes

#+hugo_weight: auto
#+hugo_auto_set_lastmod: t
#+MACRO: abbr *[$1]: $2
#+author: Matt Jones

* Link Notes                                              :@linknotes:

** Notes 11.7.2024                                     :Film:Music:
:PROPERTIES:
:EXPORT_DATE: 2024-07-11
:EXPORT_HUGO_BUNDLE: 20240711
:EXPORT_FILE_NAME: index
:END:
*** Today's notes

+ [[/blog/links/2024/07/11#shelley-duval-dies-on-her-birthday-aged-75][Shelley Duval dies on her birthday aged 75]]
+ [[/blog/links/2024/07/11#eurorack-pitch-quantizer-module-comparison][Eurorack Pitch Quantizer Module Comparison]]
+ [[/blog/links/2024/07/11#musical-connection-of-the-day][Musical connection of the day]]
  
#+begin_export hugo
<!--more-->
#+end_export
---

**** Shelley Duval dies on her birthday aged 75

https://www.theguardian.com/film/article/2024/jul/11/shelley-duvall-star-of-the-shining-and-annie-hall-dies-aged-75

I'm reassessing the way I feel about Kubrick's films, especially The Shining, which starred Shelley Duval as Wendy.

In Vivian Kubrick's 'Making of...' film we see Duvall suffering from exhaustion during the punishing filming schedule and generally being derided and put down by Kubrick, almost as a parallel to what happens in the film.

It's the sexism that we know is engrained in every industry, including the film industry.

**** Eurorack Pitch Quantizer Module Comparison

https://doudoroff.com/quantizers/

I'm currently planning my first Eurorack modular synth  and one module I need is a pitch quantizer.

A pitch quantizer translates incoming voltages to pitches in a musical scale.

This is useful if you have something generating random voltages and you want the sound this outputs to be tuneful.

THis site lists the Eurorack pitch quantizers available alongside their technical features. It's an example of a site that presents a set of very niche and detailed information in an accessible way, as opposed to the common approach these days which is to put it all into a Youtube video.  This sort of thing is the best of the Web.   


**** Musical connection of the day

The bass player on the recording of 'Histoire de Melody Nelson' by Serge Gainsbourg also played bass on the theme tune of the 1980s BBC sitcom Last of the Summer Wine. 


** Notes 8.7.2024                            :Environment:Politics:
:PROPERTIES:
:EXPORT_DATE: 2024-07-08
:EXPORT_HUGO_BUNDLE: 20240708
:EXPORT_HUGO_RESOURCES: :src "26878553260_e9d6667f6f_k.jpg" :title "Black and white photos of a wind turbine, viewed from below." :name "windturbine"
:EXPORT_FILE_NAME: index
:END:
#+begin_export hugo
{{< imgproc name="windturbine"
    command="Resize"
    options="1200x webp"
    imageCaption="Black and white photos of a wind turbine, viewed from below." 
    imageURL="https://flickr.com/photos/woolamaloo_gazette/26878553260/in/photolist-SzLEYY-SPvcVt-SPvcnV-SzLEvo-SKTMed-SKTMJ1-r4UbsZ-bUiTU2-GXaR2u-GrRMAA-2kry7bA-5rraNy-daiXty-ro6wgR-r6LzAt-2mC7HMp-bUiV1k-bUiTDX-GrRRmm-bUiTBp-GrYpki-ro6wfP-Hgm4rx-2gzq5ZX-2osWYkX-GXaBs5-bUiU2e-ppVee7-r4UbvV-rodDDB-2mC5tee-2oJBC5d-2oJC6R8-2oJzLm8-2oJwFKB-2mBZ88S-aCVkyT-2mC8SyX-2mC5tGJ-2mC4mP5-2mBZ8YK-2mC4nCz-2mC4nHe-2mBZ8LW-2mC7KFQ-2mC7Jns-2mC8TtY-2mC8Uc6-2mC8U1z-2mC7Ko5"
    imageAttrib="byronv2"
    imageLicense="(CC BY-NC 2.0)"
    licenseURL="https://creativecommons.org/licenses/by-nc/2.0/">}}
#+end_export



*** Today's notes

Some reaction to Rachel Reeves' first speech as Chancellor of the Exchequer.

+ [[/blog/links/2024/07/08#labour-lifts-tories-absurd-ban-on-onshore-windfarms][Labour lifts Tories’ ‘absurd’ ban on onshore windfarms]]: In terms of the change we need it's a drop in the warming ocean, but this is good.
+ [[/blog/links/2024/07/08#labour-s-housing-plans-will-use-green-belt-land-twice-size-of-milton-keynes-expert-says][Labour’s housing plans will use green belt land twice size of Milton Keynes, expert says]]: This one's a bit more divisive. 
+ [[/blog/links/2024/07/08#on-this-day-from-the-archive][On this day, from the archive]]: What I was listening to in 2005, toxic ships, and Spielberg's film adaption of Minority Report. 
#+begin_export hugo
<!--more-->
#+end_export
---

**** Labour lifts Tories’ ‘absurd’ ban on onshore windfarms

https://www.theguardian.com/environment/article/2024/jul/08/labour-lifts-ban-onshore-windfarms-planning-policy

I have been feeling flat about the UK election result, despite the complete trouncing of the Tories.

The result has been described as a 'sandcastle majority' and that about sums it up. It's an impressive majority on the unstable foundations of a low vote share, low turnout and Reform at Labour's heels in many Northern constituences.

This announcement from Rachel Reeves today though is a good one. We can't have infrastructure projects critical in the solutions to the climate crisis blocked by a minority of people worried about the outlook of their homes. 




---
**** Labour’s housing plans will use green belt land twice size of Milton Keynes, expert says

https://www.theguardian.com/society/article/2024/jul/08/labour-s-housing-plans-green-belt-land-new-towns-david-rudlin

Some question the need for mass-scale housebuilding when there's already enough housing stock, and the [[https://www.theguardian.com/lifeandstyle/2024/mar/19/end-of-landlords-surprisingly-simple-solution-to-uk-housing-crisis#comment-166949339][real cause of the housing crisis]] lies in Landlordism.

If new houses are to be build then we need to stop designing car dependency into these new developments. This means family housing in more compact developments that are more community oriented with transport links focused around public transport, walking and cycling.  

---
**** On this day, from the archive

+ [19 years ago: Dropping the Musical Baton](https://mattjon.es/blog/2005/07/dropping-the-musical-baton/): What I was listening to in 2005.
+ [21 years ago: The Ghost Fleet](https://mattjon.es/blog/2003/07/the-ghost-fleet/): A note about a Teesside shipyard's controversial contract to decommision some Navy ships from the US.
+ [22 years ago: Post-film](https://mattjon.es/blog/2002/07/post-film/): A short review of the Spielberg film Minority Report.  



** Notes 4.8.2023                            :Environment:Politics:
:PROPERTIES:
:EXPORT_DATE: 2023-08-04
:EXPORT_HUGO_BUNDLE: 20230804
:EXPORT_HUGO_RESOURCES: :src "27437841887_68b825ce4b_c.jpg" :title "Photo of a derelicy playground" :name "playground"
:EXPORT_FILE_NAME: index
:END:
#+begin_export hugo
{{< imgproc name="playground"
    command="Resize"
    options="1200x webp"
    imageCaption="Photo of a rusting see-saw in an overgrown playground. Image converted to monochrome from the original." 
    imageURL="https://www.flickr.com/photos/141333312@N03/27437841887/"
    imageAttrib="Trevor Marron"
    imageLicense="(CC BY 2.0)"
    licenseURL="https://creativecommons.org/licenses/by/2.0/">}}
#+end_export

*** Today's note

Thoughts on how we're denying children the natural right to play outside.
#+begin_export hugo
<!--more-->
#+end_export
---
**** England’s playgrounds crumble as council budgets fall

https://www.theguardian.com/environment/2023/aug/04/england-playgrounds-crumble-council-budgets-fall

Play is part of the physical and cognitive development of humans, other mammals and birds.

Juvenile play happens close to parents and in human society close to dwellings in communal spaces. More recently in our history, play happened in the street.

But 'developed' countries spent the latter half of the 20th Century removing these spaces and opportunity for spontanaous play. Instead, spaces for play are demarcated, usually in public parks and away from the streets where cars, both moving and parked, have become dominant.

Now, it seems, even the spaces defined as area for play are no longer maintained because of a lack of money to maintain them. Simply put, this degradation of space is against nature and against the developmental requirements of children. All while the money that should be invested in public space is funnelled into private hands for the benefit of the few.    



** Notes 14.7.2023                           :Environment:Transport:Politics:
:PROPERTIES:
:EXPORT_DATE: 2023-07-14
:EXPORT_HUGO_BUNDLE: 20230714
:EXPORT_HUGO_RESOURCES: :src "ai-image-planner.jpg" :title "VanMoof bicycle leaning against a garage door" :name "planner"
:EXPORT_HUGO_RESOURCES+: :src "stone-henge.jpg" :title "35mm film photo of Stone Henge" :name "stonehenge"
:EXPORT_FILE_NAME: index
:END:
#+begin_export hugo
{{< imgproc name="stonehenge"
    command="Resize"
    options="1200x webp"
    imageCaption="35mm film photo of Stone Henge" 
    imageURL="https://commons.wikimedia.org/wiki/File:StonehengeInfraRedE4ProcessKodakFilm-001.tif"
    imageAttrib=""
    imageLicense="Public Domain"
    licenseURL="https://en.wikipedia.org/wiki/Public_domain">}}
#+end_export
*** Today's notes

+ [[/blog/links/2023/07/14#stonehenge-tunnel-is-approved-by-government][Stonehenge tunnel is approved by government]]: Moar roads!
+ [[/blog/links/2023/07/14#wealth-taxes-will-cause-the-rich-to-flee-12-wealth-tax-myths-debunked][Wealth taxes will cause the rich to flee’: 12 wealth tax myths debunked]] The injustice of not taxing the rich

#+begin_export hugo
<!--more-->
#+end_export
---
**** Stonehenge tunnel is approved by government

https://www.bbc.co.uk/news/uk-england-wiltshire-66201424

#+begin_export hugo
{{< imgproc name="planner"
    command="Resize"
    options="1200x webp"
    imageCaption="AI generated photo of an officious looking male proudly overseeing the building of a road through the countryside" 
    imageURL="https://openai.com/dall-e-2"
    imageAttrib="DALL-e 2"
    imageLicense="Public Domain"
    licenseURL="https://en.wikipedia.org/wiki/Public_domain">}}
#+end_export

Why is the future for anything good in the world at the mercy of men - still thinking it's the 1960s - getting all excited at the prospect of taking their internal combustion engines, or possibly half-tonne lithium-ion batteries - over tarmac freshly laid over or under the countryside and, in this case, near to an ancient and globally important monument. 

This is execrable in every sense, as well as deeply irresponsible for obvious reasons. Meanwhile neighbouring Wales has simply stopped building new roads.   

---

**** Wealth taxes will cause the rich to flee’: 12 wealth tax myths debunked 

https://www.taxjustice.uk/blog/wealth-taxes-will-cause-the-rich-to-flee-11-wealth-tax-myths-debunked

For as long as I can remember - with the exception of the pandemic when there was suddenly money to pay for stuff - the government narrative around paying for public services has consistently been around the false dichotomy between austerity and raising taxes on low and middle-income earners. 

The idea of taxing the richest in society is quickly batted away by politicians regardless of which party is in power, possibly because it's the richest in society that donate large sums of money to both parties. But this couldn't be more unjust, because just a 1% tax on millionaire households over five years would raise £260 billion. That's £80 billion more than the entire NHS yearly budget. 

    

** Notes 13.7.2023                           :Cycling:Politics:Gaming:
:PROPERTIES:
:EXPORT_DATE: 2023-07-13
:EXPORT_HUGO_BUNDLE: 20230713
:EXPORT_HUGO_RESOURCES: :src "vanmoof.jpg" :title "VanMoof bicycle leaning against a garage door" :name "vanmoof"
:EXPORT_HUGO_RESOURCES+: :src "hollywood-strike.jpg" :title "Hollywood" :name "hollywood"
:EXPORT_FILE_NAME: index
:END:
#+begin_export hugo
{{< imgproc name="vanmoof"
    command="Resize"
    options="1200x webp"
    imageCaption="Photo of a white VanMoof bicycle leaning against a blue garage door" 
    imageURL="https://flickr.com/photos/kwanzshop/13849830555/"
    imageAttrib="Kwanz"
    imageLicense="CC BY 2.0"
    licenseURL="https://creativecommons.org/licenses/by/2.0/">}}
#+end_export
*** Today's notes

+ [[/blog/links/2023/07/13#bicycle-manufacture-vanmoof-is-in-trouble][VanMoof is in trouble:]] Dutch bicycle company is in financial trouble for lots of complex reasons
+ [[/blog/links/2023/07/13#akka-arrh][Akka Arrh: ]]The relaunch of a 'lost' Atari arcade game
+ [[/blog/links/2023/07/13#hollywood-actors-announce-strike-in-first-joint-action-with-writers-in-60-years][Hollywood actors announce strike in first joint action with writers in 60 years:]] Hollywood stars strike for better pay and concern about AI

#+begin_export hugo
<!--more-->
#+end_export
---
**** Bicycle manufacturer VanMoof is in trouble

https://www.dutchnews.nl/2023/07/dutch-bicycle-maker-vanmoof-granted-protection-from-creditors/

Electric-assist Pedal Cycles (EAPCs) bring with them a whole load of complexity in supply chain, manufacture and ongoing maintenance over and above the simple mechanics of a regular bicycle. 

Margins in the bike industry are tight at the best of times, however I think VanMoofs problems are partly of their own making due to the tech-heavy, proprietory nature of their products (their bikes' locking mechanism seems to use some kind of app-based encryption system) as well as their reliance on private external finance rather than being profitable. 

That said, at a time when climate action is pressing and we need people to ditch their cars, we need governments to step in and provide subsidies to help absorb these increasing supply costs, as well as lower the purchase costs  so that the bike industry in general can stay afloat. 

---
**** Akka Arrh

https://atari.com/products/akka-arrh

I'm all over this game. From the legendary Llamasoft, this is a re-imagining of a 'lost' Atari arcade game, the story of which is explained by Jeff Minter himself in [[https://www.youtube.com/watch?v=qtkifcXjJ9Q][a video uploaded to Youtube]].

Minter was approached by Atari to redevelop a game from their catalogue of arcade classics, and Akka Arrh was what he chose, the challenge being to breathe life into game that never launched.

It's available for pretty much every gaming platform thanks to Minter's partner Ivan Zorzin, who was responsible for the complex porting work.  


---
**** Hollywood actors announce strike in first joint action with writers in 60 years

https://www.theguardian.com/us-news/2023/jul/13/hollywood-actors-union-recommends-strike-as-talks-deadline-passes

#+begin_export hugo
{{< imgproc name="hollywood"
    command="Resize"
    options="1200x webp"
    imageCaption="Warner Bros. Studio during the Conference of Studio Unions strike, Los Angeles, 1945" 
    imageURL="https://digital.library.ucla.edu/catalog/ark:/21198/zz002hj471"
    imageAttrib="UCLA Charles E. Young Research Library Department of Special Collections"
    imageLicense="CC BY 4.0"
    licenseURL="https://creativecommons.org/licenses/by/4.0/">}}
#+end_export


Public Sector worker strikes for better pay and conditions are now a common occurance here in the UK because of our dreadful government who treat people who work in public service abysmally.

Now Hollywood actors are on strike for the first joint action with writers in over 60 years. Because the dynamics of exchanging labour for wage payment are the same regardless of the sectors you work in. 


** Link Notes 10 March 2023                  :Politics:Herne:BBC:
:PROPERTIES:
:EXPORT_DATE: 2023-03-10
:EXPORT_HUGO_BUNDLE: 20230310
:EXPORT_HUGO_RESOURCES: :src "herne.jpg" :title "Herne the Hunter" :name "herne"
:EXPORT_FILE_NAME: index
:END:
#+begin_export hugo
{{< imgproc name="herne"
    command="Resize"
    options="1200x webp"
    imageCaption="1840s illustration of Herne the Hunter riding a horse" 
    imageURL="https://commons.wikimedia.org/wiki/File:Herne_the_Hunter.jpg"
    imageAttrib="Wikimedia Commons"
    imageLicense="Public Domain"
    licenseURL="">}}
#+end_export
*** Today's links

What I'm thinking about today. Interested in the power of music and memory, or how the former can trigger the latter. Also, crisis at the BBC.  

+ [[/blog/links/2023/03/10#herne-the-hunter][Herne the Hunter]]: Pagan myths, social justice and 80s TV
+ [[/blog/links/2023/03/10#gary-lineker-andrew-neil-and-the-bbc-s-real-impartiality-crisis][Gary Lineker, Andrew Neil and the BBC’s Real Impartiality Crisis]]: The right-wing free-speech hyprocrites
+ [[/blog/links/2023/03/10#on-this-day-from-the-archive][On this day, from the archive]]: Nautilus Goes Spatial
#+begin_export hugo
<!--more-->
#+end_export

**** Herne the Hunter

https://en.wikipedia.org/wiki/Herne_the_Hunter

I've been thinking about my happy childhood; the long summers, the freedom, the predictable weather, the constructive boredom associated with the contraints of only four television channels. There's one particular programme (and its soundtrack) that reminds me of this period more than anything. 'Robin of Sherwood' was an influential ITV adaption of Robin Hood, introducing pagan mythology into its story of struggle against oppression. 

The mythical figure Herne is presented as a sort of commissioner for Robin Hood to protect the poor against the oppressive regime of the Sherriff of Nottingham. His appearance in the series was accompanied by  ambient and arpeggiated synth sounds by the band Clannad, who provided the sound track to the series. It's this track in particular that transports me to a specific time and place: a bedroom on a hot summer evening (in around 1985), standing in front of a tape deck and reading the album sleeve notes from the soundtrack.

Thinking about writing a longer post about this particular depiction of Herne.  

---

**** Gary Lineker, Andrew Neil and the BBC’s Real Impartiality Crisis

https://bylinetimes.com/2023/03/09/gary-lineker-andrew-neil-and-the-bbcs-real-impartiality-crisis/

Adam Bienkov lays bare the rank hypocrisy shown by the right wing in relation to BBC impartiality. 

---

**** On this day, from the archive

+ [19 years ago: Nautilus Goes Spatial](https://mattjon.es/blog/2004/03/nautilus-goes-spatial/): I've been a Linux user for about 25 years. Here are some thought about changes' to Gnome's file manager, created by Andy Hertzfeld (who helped to create the user interface on the original Apple Macintosh). 



** Link Notes 8 March 2023                   :Politics:Asylum:Blogging:
:PROPERTIES:
:EXPORT_DATE: 2023-03-08
:EXPORT_HUGO_BUNDLE: 20230308
:EXPORT_FILE_NAME: index
:END:
*** Today's links
+ [[/blog/links/2023/03/08#rishi-sunak-extinguishing-the-right-to-seek-refugee-protection-in-uk][Rishi Sunak ‘extinguishing the right to seek refugee protection in UK’]]: Stop the Tories
+ [[/blog/links/2023/03/08#ox-hugo-org-to-markdown-for-hugo][Ox-Hugo]]: My somewhat esoteric blogging system of choice
+ [[/blog/links/2023/03/08#on-this-day-from-the-archive][On this day, from the archive]]: The Internet Book List
#+begin_export hugo
<!--more-->
#+end_export

**** Rishi Sunak ‘extinguishing the right to seek refugee protection in UK’

https://www.theguardian.com/uk-news/2023/mar/07/suella-braverman-asylum-migration-bill-law-change-small-boats

The United Kingdom has a long history of welcoming and protecting those seeking refuge from conflict and persecution around the world. It's why the UK is a diverse place.

Sunak and Braverman are pandering to the extreme-right with this disgusting plan to criminalise desperate people seeking a better life. 

Shame on all involved.  

---

**** Ox-Hugo: Org to Markdown for Hugo

https://ox-hugo.scripter.co

For quite a number of years now, this site has been produced using a static-site generator called Hugo. I write Markdown files, run 'hugo' and and within a fraction of a second 1800+ posts are packaged up into a set of HTML files ready to deploy. If that wasn't esoteric enough, I use Emacs with Org Mode to write and manage my posts in one .org file. OrgMode is basically a todo / planner system for Emacs with lots of nerdy features that I'll never use or fully understand.   






---

**** On this day, from the archive

+ [20 years ago: The Internet Book List](https://mattjon.es/blog/2003/03/the-internet-book-list/): A note on the launch of the Internet Book List: a sort of IMDB for books. 



* Code
(defun hugo-slugify (start end)
  (interactive "r")
  (if (use-region-p)
      (let ((regionp (buffer-substring start end)))
        (save-excursion
          (delete-region start end)
          (insert
           (replace-regexp-in-string
            "[^a-z0-9-]" ""
            (replace-regexp-in-string
             "\s+" "-"
             (downcase regionp)
             )))))))

* Footnotes
* COMMENT Local Variables                                           :ARCHIVE:
# Local Variables:
# org-hugo-footer: "\n\n[//]: # \"Exported with love from a post written in Org mode\"\n[//]: # \"- https://github.com/kaushalmodi/ox-hugo\""
# End:


